DROP TABLE book;
DROP TABLE location;
DROP TABLE author;
DROP TABLE genre;

CREATE TABLE public.location
(
	id SERIAL NOT NULL PRIMARY KEY,
	location VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE public.author
(
	id SERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);
CREATE TABLE public.genre
(
	id SERIAL  NOT NULL PRIMARY KEY,
	genre VARCHAR(25) NOT NULL
);
CREATE TABLE public.book
(
	id SERIAL  NOT NULL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	author INT NOT NULL REFERENCES public.author(id),
	genre INT NOT NULL REFERENCES public.genre(id),
	location INT NOT NULL REFERENCES public.location(id)
);

INSERT INTO location VALUES (DEFAULT,'Bookcase in Den Left');
INSERT INTO location VALUES (DEFAULT,'Bookcase in Den Right');
INSERT INTO location VALUES (DEFAULT,'Barrister Bookcase West');
INSERT INTO location VALUES (DEFAULT,'Barrister Bookcase');
INSERT INTO location VALUES (DEFAULT,'Guest Bedroom');
INSERT INTO location VALUES (DEFAULT,'STE Michelle Shopping Bag');

INSERT INTO genre VALUES (DEFAULT,'Comedy');
INSERT INTO genre VALUES (DEFAULT,'Biography');
INSERT INTO genre VALUES (DEFAULT,'Fiction');
INSERT INTO genre VALUES (DEFAULT,'Travel');
INSERT INTO genre VALUES (DEFAULT,'Art');
INSERT INTO genre VALUES (DEFAULT,'Children Books');
INSERT INTO genre VALUES (DEFAULT,'Cooking');
INSERT INTO genre VALUES (DEFAULT,'Health');
INSERT INTO genre VALUES (DEFAULT,'History');
INSERT INTO genre VALUES (DEFAULT,'Puzzles');
INSERT INTO genre VALUES (DEFAULT,'Home & Garden');
INSERT INTO genre VALUES (DEFAULT,'Poems');
INSERT INTO genre VALUES (DEFAULT,'Self-Improvement');
INSERT INTO genre VALUES (DEFAULT,'Animals & Nature');

INSERT INTO author VALUES (DEFAULT,'AAA');
INSERT INTO author VALUES (DEFAULT,'ADKINS, ROY & LESLEY');
INSERT INTO author VALUES (DEFAULT,'ALWAYS,  JONATHAN');
INSERT INTO author VALUES (DEFAULT,'ANDREWS, JULIE');
INSERT INTO author VALUES (DEFAULT,'ARIAS, RON');
INSERT INTO author VALUES (DEFAULT,'ATTENBOROUGH, DAVID');
INSERT INTO author VALUES (DEFAULT,'AUEL, JEAN M.');
INSERT INTO author VALUES (DEFAULT,'AUSTEN, JANE');
INSERT INTO author VALUES (DEFAULT,'AZ-SONORA DESERT MUSEUM');
INSERT INTO author VALUES (DEFAULT,'BACH, RICHARD');
INSERT INTO author VALUES (DEFAULT,'BENCE-JONES, MARK');
INSERT INTO author VALUES (DEFAULT,'BENNETT, WM. J.');
INSERT INTO author VALUES (DEFAULT,'BERGAN, RONALD');
INSERT INTO author VALUES (DEFAULT,'BICKNELL & PAGE, JOANNA & NICK');
INSERT INTO author VALUES (DEFAULT,'BILL BRYSON');
INSERT INTO author VALUES (DEFAULT,'BLACK, JEREMY');
INSERT INTO author VALUES (DEFAULT,'BLANDING, DON');
INSERT INTO author VALUES (DEFAULT,'BRADFORD, SARAH');
INSERT INTO author VALUES (DEFAULT,'BROKAW, TOM');
INSERT INTO author VALUES (DEFAULT,'BRONTE, ANNE');
INSERT INTO author VALUES (DEFAULT,'BRONTE, CHARLOTTE');
INSERT INTO author VALUES (DEFAULT,'BRONTE, EMILY');
INSERT INTO author VALUES (DEFAULT,'BRYSON, GILL');
INSERT INTO author VALUES (DEFAULT,'BUSH, GEORGE W.');
INSERT INTO author VALUES (DEFAULT,'BYRDE, PENELOPE');
INSERT INTO author VALUES (DEFAULT,'CALDWELL TAYLOR');
INSERT INTO author VALUES (DEFAULT,'CARLSON, RICHARD [ph.d]');
INSERT INTO author VALUES (DEFAULT,'CARROLL, LESLIE');
INSERT INTO author VALUES (DEFAULT,'CARTER, JIMMY');
INSERT INTO author VALUES (DEFAULT,'CHILD, LEE');
INSERT INTO author VALUES (DEFAULT,'CHILDS, CRAIG');
INSERT INTO author VALUES (DEFAULT,'CHRISTIE, AGATHA');
INSERT INTO author VALUES (DEFAULT,'CLASSIC');
INSERT INTO author VALUES (DEFAULT,'CLWYD');
INSERT INTO author VALUES (DEFAULT,'COBB, VICKI');
INSERT INTO author VALUES (DEFAULT,'CONNEY, BARBARA');
INSERT INTO author VALUES (DEFAULT,'CONSUMER REPORTS');
INSERT INTO author VALUES (DEFAULT,'COUNTESS OF CARNARVON');
INSERT INTO author VALUES (DEFAULT,'COVEY, STEVEN R.');
INSERT INTO author VALUES (DEFAULT,'COVINGTON JR, HOWARD E.');
INSERT INTO author VALUES (DEFAULT,'CRAYOLA');
INSERT INTO author VALUES (DEFAULT,'DE LOS SANTOS, MARISA');
INSERT INTO author VALUES (DEFAULT,'DEARY, TERRY');
INSERT INTO author VALUES (DEFAULT,'DELDERFIELD, ERIC R.');
INSERT INTO author VALUES (DEFAULT,'DEWBERRY, DONNA');
INSERT INTO author VALUES (DEFAULT,'DISNEY');
INSERT INTO author VALUES (DEFAULT,'DR. SEUSS');
INSERT INTO author VALUES (DEFAULT,'ELIOT, GEORGE');
INSERT INTO author VALUES (DEFAULT,'ENGLAND / WITNEY, OXFORD');
INSERT INTO author VALUES (DEFAULT,'ENGLISH HERITAGE');
INSERT INTO author VALUES (DEFAULT,'EVANS, RICHARD PAUL');
INSERT INTO author VALUES (DEFAULT,'FAIRVIEW REFORMED CHURCH');
INSERT INTO author VALUES (DEFAULT,'FAIRVIEW, MONICA');
INSERT INTO author VALUES (DEFAULT,'FELLOWES, JESSICA');
INSERT INTO author VALUES (DEFAULT,'FIFER, BARBARA');
INSERT INTO author VALUES (DEFAULT,'FILEY, JAMES WHITCOMB');
INSERT INTO author VALUES (DEFAULT,'FLAGG, FANNIE');
INSERT INTO author VALUES (DEFAULT,'FLYNN, VINCE');
INSERT INTO author VALUES (DEFAULT,'FORSTER, E.M.');
INSERT INTO author VALUES (DEFAULT,'FROST, ROBERT');
INSERT INTO author VALUES (DEFAULT,'GARDNER, ERLE STANLEY');
INSERT INTO author VALUES (DEFAULT,'GARNER');
INSERT INTO author VALUES (DEFAULT,'GARNER, VALERIE');
INSERT INTO author VALUES (DEFAULT,'GIES, FRANCES & JOSEPH');
INSERT INTO author VALUES (DEFAULT,'GOODWIN, DORIS KEARNS');
INSERT INTO author VALUES (DEFAULT,'GRAHAME, KENNETH');
INSERT INTO author VALUES (DEFAULT,'GRAY, DONNA');
INSERT INTO author VALUES (DEFAULT,'GREGORY, FAY');
INSERT INTO author VALUES (DEFAULT,'GREY, ZANE');
INSERT INTO author VALUES (DEFAULT,'GRISHAM, JOHN');
INSERT INTO author VALUES (DEFAULT,'GUERNEY, JAMES');
INSERT INTO author VALUES (DEFAULT,'GUINNESS');
INSERT INTO author VALUES (DEFAULT,'GUTERSON, DAVID');
INSERT INTO author VALUES (DEFAULT,'HALEY, ALEX');
INSERT INTO author VALUES (DEFAULT,'HARDY, THOMAS');
INSERT INTO author VALUES (DEFAULT,'HARRIOT, JAMES');
INSERT INTO author VALUES (DEFAULT,'HARRISON, SUE');
INSERT INTO author VALUES (DEFAULT,'HAWTHORNE, NATHANIAL');
INSERT INTO author VALUES (DEFAULT,'HEINRICH, CHRISTOPH');
INSERT INTO author VALUES (DEFAULT,'HELPRIN, MARK');
INSERT INTO author VALUES (DEFAULT,'HENRY, MARGUERITE');
INSERT INTO author VALUES (DEFAULT,'HEYER, GEORGETTE');
INSERT INTO author VALUES (DEFAULT,'HOBAN, LILLIAN');
INSERT INTO author VALUES (DEFAULT,'IRISH, MARY');
INSERT INTO author VALUES (DEFAULT,'ISAACSON, WALTER');
INSERT INTO author VALUES (DEFAULT,'JONES, WARREN');
INSERT INTO author VALUES (DEFAULT,'KARON, JAN');
INSERT INTO author VALUES (DEFAULT,'KAYE, M.M.');
INSERT INTO author VALUES (DEFAULT,'KEENE, CAROLYN');
INSERT INTO author VALUES (DEFAULT,'KIDD, SUE MONK');
INSERT INTO author VALUES (DEFAULT,'KIERNAN, DENISE');
INSERT INTO author VALUES (DEFAULT,'KINCAID, THOMAS');
INSERT INTO author VALUES (DEFAULT,'KINGSOLVER, BARBARA');
INSERT INTO author VALUES (DEFAULT,'KIPLING, RUDYARD');
INSERT INTO author VALUES (DEFAULT,'LEROUX, GASTON');
INSERT INTO author VALUES (DEFAULT,'LIFE MAGAZINE');
INSERT INTO author VALUES (DEFAULT,'LINDGREN, ASTRID');
INSERT INTO author VALUES (DEFAULT,'LITTLE GOLDEN BOOK');
INSERT INTO author VALUES (DEFAULT,'LOBEL, ARNOLD');
INSERT INTO author VALUES (DEFAULT,'LONDON, JACK');
INSERT INTO author VALUES (DEFAULT,'LONELY PLANET');
INSERT INTO author VALUES (DEFAULT,'LONGFELLOW, HENRY WADSWORTH');
INSERT INTO author VALUES (DEFAULT,'LORD MONTAGU OF BEAULIEU');
INSERT INTO author VALUES (DEFAULT,'MARKLE, SANDRA');
INSERT INTO author VALUES (DEFAULT,'MARTEL, YANN');
INSERT INTO author VALUES (DEFAULT,'MARTIN & MARTIN');
INSERT INTO author VALUES (DEFAULT,'MC MAUGHTON, COLIN');
INSERT INTO author VALUES (DEFAULT,'MILLARD, CANDICE');
INSERT INTO author VALUES (DEFAULT,'MILLMAN');
INSERT INTO author VALUES (DEFAULT,'MITCHELL, MARGARET');
INSERT INTO author VALUES (DEFAULT,'MOELLER, BILL & JAN');
INSERT INTO author VALUES (DEFAULT,'MOLLY MAID');
INSERT INTO author VALUES (DEFAULT,'MONTGOMERY, L.M.');
INSERT INTO author VALUES (DEFAULT,'MONTGOMERY, LUCY MAUD');
INSERT INTO author VALUES (DEFAULT,'MORTENSON & RELIN');
INSERT INTO author VALUES (DEFAULT,'MUIR, FRANK');
INSERT INTO author VALUES (DEFAULT,'MUNSCH, ROBERT');
INSERT INTO author VALUES (DEFAULT,'NATIONAL GEOGRAPHIC GUIDE');
INSERT INTO author VALUES (DEFAULT,'NEIDER, CHARLES  (EDITOR)');
INSERT INTO author VALUES (DEFAULT,'NEILLANDS, ROB');
INSERT INTO author VALUES (DEFAULT,'NIFFENEGGER, AUDREY');
INSERT INTO author VALUES (DEFAULT, 'O HENRY');
INSERT INTO author VALUES (DEFAULT,'PARKER, TOM');
INSERT INTO author VALUES (DEFAULT,'PAT, B   &   THOMPSON, J');
INSERT INTO author VALUES (DEFAULT,'PATTERSON, JAMES');
INSERT INTO author VALUES (DEFAULT,'PEARS, IAIN');
INSERT INTO author VALUES (DEFAULT,'PECK, RICHARD');
INSERT INTO author VALUES (DEFAULT,'PENMAN, SHARON KAY');
INSERT INTO author VALUES (DEFAULT,'PHILLIPS, GERALD');
INSERT INTO author VALUES (DEFAULT,'PITKIN GUIDES');
INSERT INTO author VALUES (DEFAULT,'POST, ELIZABETH L.');
INSERT INTO author VALUES (DEFAULT,'POTTER, BEATRICE');
INSERT INTO author VALUES (DEFAULT,'QUANTE, DON');
INSERT INTO author VALUES (DEFAULT,'QUEEN, ELLERY');
INSERT INTO author VALUES (DEFAULT,'RAND MC NALLY');
INSERT INTO author VALUES (DEFAULT,'RANDOM HOUSE');
INSERT INTO author VALUES (DEFAULT,'READERS DIGEST');
INSERT INTO author VALUES (DEFAULT,'REICHL, RUTH');
INSERT INTO author VALUES (DEFAULT,'ROBERTS, COKIE');
INSERT INTO author VALUES (DEFAULT,'ROHINTON MISTRY');
INSERT INTO author VALUES (DEFAULT,'ROTHENBERG, REBECCA');
INSERT INTO author VALUES (DEFAULT,'RUTHERFURD, EDWARD');
INSERT INTO author VALUES (DEFAULT,'SARABANDE, WILLIAM');
INSERT INTO author VALUES (DEFAULT,'SCOTT, SIR WALTER');
INSERT INTO author VALUES (DEFAULT,'SEARS');
INSERT INTO author VALUES (DEFAULT,'SEDGWICK, ANN DOUGLAS');
INSERT INTO author VALUES (DEFAULT,'SERLING, ROBERT J.');
INSERT INTO author VALUES (DEFAULT,'SLATER & BASCH, SHIRLEY & HARRY');
INSERT INTO author VALUES (DEFAULT,'SLAYBAUGH, THOMAS JACKSON');
INSERT INTO author VALUES (DEFAULT,'SPENCER, CHARLES');
INSERT INTO author VALUES (DEFAULT,'STEINBECK, JOHN');
INSERT INTO author VALUES (DEFAULT,'STEVENSON, ROBERT LOUIS');
INSERT INTO author VALUES (DEFAULT,'STEVES, RICK');
INSERT INTO author VALUES (DEFAULT,'STEWART, JON');
INSERT INTO author VALUES (DEFAULT,'STONE, IRVING');
INSERT INTO author VALUES (DEFAULT,'SUNSET');
INSERT INTO author VALUES (DEFAULT,'SYNYARD, NEAL');
INSERT INTO author VALUES (DEFAULT,'THOM, JAMES ALEXANDER');
INSERT INTO author VALUES (DEFAULT,'THOMAS, ROGER');
INSERT INTO author VALUES (DEFAULT,'TIERNEY, TOM');
INSERT INTO author VALUES (DEFAULT,'TIME / CBS NEWS');
INSERT INTO author VALUES (DEFAULT,'TRAPP, MARIA AUGUSTA');
INSERT INTO author VALUES (DEFAULT,'TRUMAN, MARGARET');
INSERT INTO author VALUES (DEFAULT,'UNICHROME PUBLICATION');
INSERT INTO author VALUES (DEFAULT,'UNKNOWN');
INSERT INTO author VALUES (DEFAULT,'URBANSKA & LEVERING');
INSERT INTO author VALUES (DEFAULT,'VEREY, ROSEMARY');
INSERT INTO author VALUES (DEFAULT,'VOLKMANN, ROY');
INSERT INTO author VALUES (DEFAULT,'WALDO, ANNA LEE');
INSERT INTO author VALUES (DEFAULT,'WALKER, STEVEN L.');
INSERT INTO author VALUES (DEFAULT,'WEINER, JONATHAN');
INSERT INTO author VALUES (DEFAULT,'WEIR, ALISON');
INSERT INTO author VALUES (DEFAULT,'WELLS, H. G.');
INSERT INTO author VALUES (DEFAULT,'WHITE, PHIL & CAROL');
INSERT INTO author VALUES (DEFAULT,'WIGGIN, KATE DOUGLAS');
INSERT INTO author VALUES (DEFAULT,'WILLIAMS, MARGERY');
INSERT INTO author VALUES (DEFAULT,'YORK, ROBERT');

INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, '… AND LADIES OF THE CLUB',165,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, '175TH ANNIVERSARY OF THE FAIRVIEW REFORMED CHURCH',165,9,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, '63 SHORT STORIES',134,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'A CHILDS GARDEN OF VERSES',152,6,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'A COMMON LIFE',87,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'A COUNTRY WOMANS YEAR',167,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'A DAY ON THE FARM',98,6,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'A FINE BALANCE',140,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'A LUCKY LIFE INTERRUPTED',19,2,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'A MEDIEVAL FAMILY',64,9,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'A REDBIRD CHRISTMAS',57,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'A YEAR OF RADIANT LIGHT',92,5,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ABC    [ FOLD-A-BOOK ]',41,6,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ALL AROUND AMERICA',135,4,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ALL THINGS WISE & WONDERFUL',76,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ALTHROP',150,3,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'AMERICAN CITIZEN GUIDE TO DEMOCRATIC INACTION',154,1,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'AN IRREVERENT & THOROUGHLY INCOMPLETE SOCIAL HISTORY OF ALMOST EVERYTHING',116,9,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'AN UNCOMMON HX OF COMMON THINGS',142,9,6);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ANIMALS MARCO POLO SAW',104,9,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ANNE OF GREEN GABLES',113,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ANNE OF GREEN GABLES [ + 2 MORE ]',114,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ARIZONA    ',170,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ARIZONA & NEW MEXICO',1,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ARIZONA GARDENERS GUIDE',84,11,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ART OF THE PRE-RAPHAELITES, THE',165,5,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ARTHURS CHRISTMAS COOKIES',83,7,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ARTHURS HONEY BEAR',83,6,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ARTHURS PRIDE READER',83,6,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'AT HOME',15,4,6);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ATLAS OF WORLD HISTORY',165,9,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'AUTOBIOGRAPHY OF HENRY VIII',172,2,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'BENJAMIN FRANKLIN',85,2,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'BEST LOVED POEMS OF THE AMERICAN PEOPLE, THE',165,12,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'BEST OF DISNEY, THE',157,6,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'BEYOND THE GARDEN GATE',92,5,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'BEYOND THE SEA OF ICE',143,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'BIG BOOK OF ADVENTURE, THE',165,4,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'BILTMORE - AMERICAN MASTERPIECE',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'BLENHEIM PALACE',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'BOOK OF VIRTUES, THE',12,13,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'BRIGHTY OF THE GRAND CANYON',81,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'BUILDING A CLASSICAL MUSIC LIBRARY',165,5,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'BUNGALOW MYSTERY, THE [Nancy Drew]',89,6,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CANT WAIT TO GET TO HEAVEN',57,13,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CAPTAINS & THE KINGS',26,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CHATSWORTH - DEVONSHIRE',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CHATSWORTH GARDEN - DEVONSHIRE',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CHILDREN OF HENRY VIII, THE',172,9,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CHIRK CASTLE ',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CLAN OF THE CAVE BEAR, THE',7,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CLASSIC MURDER MYSTERIES',32,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CLASSIC WESTERNS',69,3,6);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CLASSICS',78,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CLASSICS',122,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CLEAN LIKE THE PROS ',112,11,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CONSENT TO KILL',58,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'CURIOUS KITTENS',168,6,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'DARCY COUSINS, THE',53,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'DECISION POINTS',24,2,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'DESTINY..of the REPUBLIC/Garfield',108,6,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'DIANA PRINCESS OF WALES / PAPER DOLL',160,6,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'DIE TRYING [Jack Reacher]',30,6,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'DINOTOPEA',71,6,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'DISNEY CLASSIC COLLECTION',46,6,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'DONT GO BROKE IN A NURSING HOME',133,13,6);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'DONT SWEAT THE SMALL STUFF',27,13,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'EASY DOES IT  (household problems)',165,11,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ELIZABETH',18,3,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'EMILY POSTS ETIQUETTE [15TH ED.]',131,12,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'EMMA',8,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ENGLISH HERITAGE',103,9,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ERDDIG - THE NATIONAL TRUST',34,9,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'EUROPE THROUGH THE BACK DOOR',153,4,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'FALLS THE SHADOW',128,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'FAMILY WORLD ATLAS',145,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'FIRST LADIES',163,9,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'FOLLOW THE RIVER',158,9,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'FORBIDDEN LAND',143,9,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'FOUNDING MOTHERS',139,9,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'FOUR BLIND MICE',125,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'FRIED GREEN TOMATOES….',57,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'FROM SEA TO SHINING SEA',158,9,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'FULL-TIME RV-ING',111,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'GARDEN DIARY…',167,11,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'GARLIC AND SAPPHIRES',138,7,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'GEORGIA, NORTH and SOUTH CAROLINA',1,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'GIANT TREASURY OF BEATRICE POTTER',132,6,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'GLAMOROUS MUSICALS',13,5,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'GONE WITH THE WIND',110,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'GREAT BIBLE STORIES & MASTER PAINTINGS',165,5,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'GREAT BRITAIN & IRELAND / 2000',153,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'GREAT ENGLISH HOUSES',11,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'GUINNESS ... WORLD RECORDS 2001',72,9,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HARRY S. TRUMAN',163,2,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HELP FOR SHY PEOPLE',129,13,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HERE BE DRAGONS',128,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HERE LIES THE LIBRARIAN',127,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HERITAGE OF THE DESERT, THE ',69,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HIDDEN STAIRCASE, THE            [Nancy Drew]',89,6,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HIGHLY EFFECTIVE PEOPLE (habits)',39,13,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HISTORY OF BRITISH ISLES',16,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HOLY BIBLE',165,13,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HOLY BIBLE   (zippered)',165,13,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HOLY BIBLE  ( KING JAMES )',52,13,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HOLY BIBLE  ( REVISED STANDARD )',165,13,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HOME    [ A MEMOIR…. ]',4,2,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HOME IS WHERE THE HEART IS',92,5,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HORNETS NEST, THE',29,2,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HOW TO CLEAN PRACTICALLY ANYTHING',37,11,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HOWARDS END',59,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HUNCHBACK OF NOTRE DAME',46,6,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'HYMNAL, THE',165,5,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ILLUSTRATED HERB ENCYCLOPEDIA, THE',165,11,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'IMAGES OF ILLINOIS',165,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'IN & AROUND CHESTER ( ENGLAND )',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'IN THE COMPANY OF OTHERS',87,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'INSTANCE OF THE FINGERPOST, THE',126,3,6);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'JACK LONDON -  CALL OF THE WILD, WHITE FANG, THE SEA-WOLF',100,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'JAMES HARRIOTS YORKSHIRE',76,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'JANE AUSTEN INFO',165,2,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'JANE AUSTEN, 101 THINGS YOU DIDNT KNOW ABOUT…',165,2,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'JANE AUSTENS ENGLAND',2,4,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'JANE AUSTIN FASHION',25,9,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'JANE EYRE',21,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'JONATHAN LIVINGSTON SEAGULL',10,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'JOURNEY THROUGH ENGLAND',120,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'JOURNEY THROUGH WALES',159,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'JULIUS CAESARS INTERESTING BITS',68,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'JUST SO STORIES',94,3,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'KENSINGTON PALACE GUIDEBOOK',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'KILLING FLOOR [Jack Reacher]',30,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'KINGS & QUEENS OF ENGLAND',44,9,6);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LACUNA, THE',93,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LADY ALMINA & THE REAL DOWNTOWN',38,9,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LADY ON THE HILL    [ BILTMORE ]',40,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LAND OF PAINTED CAVES, THE',7,4,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LANDSCAPE PLANTS FOR DRY REGIONS ',86,11,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LANDSCAPING FOR SMALL SPACES',156,11,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LAST CASTLE, THE',91,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LEGEND & LEGACY  [ BOEING ]',147,9,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LEWIS & CLARK',55,9,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LIFE AND WORKS OF BOTTICELLI, THE',165,5,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LIFE AND WORKS OF RENOIR, THE',165,5,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LIFE OF PI',105,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LIGHT FROM HEAVEN',87,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LITTLE FRENCH  GIRL, THE',146,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LIVE YOUR ROAD TRIP DREAM',174,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LIVING PLANET, THE',6,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LONG KNIFE',158,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LONGFELLOW POEMS….',102,12,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LOVE POEMS FOR THE VERY MARRIED',165,12,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LOVE WALKED IN',42,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'LOVE YOU FOREVER',117,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MADE IN AMERICA',23,9,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MARK TWAIN, AUTOBIOGRAPHY',119,2,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MARVELS & MYSTERIES OF OUR ANIMAL WORLD',165,14,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MATHEMAGIC',33,13,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MIDDLEMARCH',48,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MIDNIGHT LINE, THE   [Jack Reacher ]',30,3,6);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MISS RUMPHIUS',36,3,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MOJAVE',149,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MONET',79,5,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MOTHER EARTH FATHER SKY',77,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MOUSETON ABBEY / MISSING DIAMOND',14,3,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MOVING TARGET',5,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MOVING TO A SMALL TOWN',166,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MURDER ON THE ORIENT EXPRESS',32,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MURDER ON THE POTOMAC',163,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MY BOOK ABOUT ME',47,6,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'MYSTERY AT LILAC INN, THE [Nancy Drew]',89,3,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'NEVER TRUST A CALM DOG',123,13,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'NIGHT FLIGHT TO FREEDOM',149,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'NIGHT SCHOOL [ Jack Reacher ]',30,3,6);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'NO MIDDLE NAME [Jack Reacher ]',30,3,6);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'NO ORDINARY TIME',65,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'NORD, SHANNON & MATT   9/28/2004',165,2,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'NOTHING TO TELL',67,3,6);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'NOTORIUS ROYAL MARRIAGES',28,9,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'OAHU REVEALED',1,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ONCE UPON A MORE ENLIGHTED TIME',62,4,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ONE-STROKE LANDSCAPES',45,11,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'OUR AMAZING WORLD OF NATURE',165,14,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'OUT TO OLD AUNT MARYS',56,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'OUTLINE OF HISTORY II, THE ',173,9,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'OVER BATH  (GUIDEBOOK)',164,11,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'OWL AT HOME',99,6,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'PAST TIMES - EASTER 2000',49,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'PAST TIMES - SUMMER 2000',49,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'PEOPLE OF THE CENTURY',161,9,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'PHANTON OF THE OPERA',95,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'PICTURE DICTIONARY',98,6,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'PIPPI IN THE SOUTH SEAS',97,6,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'PLANET EARTH',171,14,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'POISONWOOD BIBLE, THE',93,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'PRACTICAL GUIDE TO HOME LANDSCAPING',137,11,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'PRESIDENTS HOUSE, THE',163,9,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'PRIDE & PREJUDICE',8,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'PUZZLES FOR PUZZLERS',3,10,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'QUEEN ELIZABETH, THE QUEEN MOTHER*',63,2,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'RAILWAY CHILDREN, THE',165,6,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'READERS DIGEST magazine',165,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'REALM - A VICTORIAN CHRISTMAS',165,3,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'REALM - FAVOURITE ENGLISH VILLAGES',165,3,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'REBECCA OF SUNNYBROOK FARM',175,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ROBERT FROST, THE POETRY OF',60,12,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ROOTS',74,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ROYAL WEDDING (WM & KATE)',96,2,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ROYAL WEDDING, THE (WM & KATE)',165,2,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'RV VACATIONS …. FOR DUMMIES',148,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SACAJAWEA',169,2,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SARUM',142,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SAVAGE STONE AGE, THE ',43,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SCENIC HIWAYS & BYWAYS',118,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SECRET LIFE OF BEES, THE',90,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SECRET LIVES OF HUMMINGBIRDS',9,3,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SENSE & SENSIBILITY',8,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SHY TULIP MURDERS',141,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SIMPLER TIMES',92,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SKIPPING CHRISTMAS',70,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SNOW FALLING ON CEDARS',73,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SOMEWHERE SAFE WITH SOMEONE GOOD',87,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SOUTHERN CALIFORNIA TRAVEL GUIDE',156,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SOUTHWESTS CONTRARY LAND, THE',31,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SPANISH IN 10 MINUTES A DAY',165,13,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SPANISH,  OPEN DOOR TO…',165,13,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SPANISH, 50 VERBS',165,13,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SPANISH/ENGLISH DICTIONARY',136,13,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'ST. PAULSS CATHEDRAL GUIDEBOOK',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'STONEHENGE',50,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'STORY OF THE GLOBE, THE',165,9,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SWAN LAKE',80,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'SWORD OF DECEMBER, THE ',177,3,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'TALE OF GINGER & PICKLES',132,3,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'TENANT OF WILDFIELD HALL, THE',20,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'TESS OF THE DURBERVILLES',75,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'THE AFFAIR  [Jack Reacher]',30,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'THE CHRISTMAS CANDLE',51,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'THE LORD GOD MADE THEM ALL',76,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'THE PARTNER',70,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'THE PRESIDENTS LADY',155,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'THE QUEENS MAN',128,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'THE RECKONING',128,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'THE RED PONY',151,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'THE USA QUESTIONS & ANSWERS ENCYCLOPEDIA',165,9,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'THE WORLD OF DOWNTOWN ABBEY',54,4,6);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'THIS PLACE IS DRY',35,4,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'THREE CUPS OF TEA',115,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'TIME TRAVELERS WIFE, THE',121,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'TOURING ENGLAND',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'TOWER OF LONDON, THE GUIDEBOOK',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'TRADE WINDS',88,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'TRAPP FAMILY SINGERS, THE STORY OF',162,3,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'TWO CLUES',61,3,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'UNDISCOVERED AMERICA',106,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'UPS & DOWNS OF A DONKEYS LIFE, THE',165,6,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'USA BEST TRIPS',101,4,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'USE THE RIGHT WORD',165,13,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'VAGABONDS HOUSE',17,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'VELVETEEN RABBIT, THE',176,6,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WALES CASTLES & HISTORICAL PLACES',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WARS OF THE ROSES, THE',172,3,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WAVERLY',144,3,4);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WAY OF THE PEACEFUL WARRIOR',109,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WELSH PLACE NAMES',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WHAT AM I  ?',98,6,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WHODUNITS',33,10,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WHOS BEEN SLEEPING IN MY PORRIDGE    ',107,6,1);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WILLIAM & CATHERINE / ROYAL WEDDING',130,2,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WILLIAM SHAKESPEARE, Complete Works',165,3,3);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WIND IN THE WILLOWS',66,6,5);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WINDSOR CASTLE OFFICIAL GUIDE',165,4,2);
INSERT INTO book (id, title, author, genre, location) VALUES (DEFAULT, 'WUTHERING HEIGHTS',22,3,4);




